---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: devices.domotik8s.io
spec:
  group: domotik8s.io
  versions:
    - name: v1beta1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            # SPEC
            spec:
              type: object
              properties:
                # PROPERTIES
                properties:
                  type: object
                  properties:
                    # BOOLEAN
                    boolean:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                      # PROPERTYSPEC
                      additionalProperties:
                        type: object
                        properties:
                          # ADDRESS
                          address:
                            type: object
                            x-kubernetes-preserve-unknown-fields: true
                            properties:
                              system:
                                type: string
                              instance:
                                type: string
                          semantic:
                            type: object
                            properties:
                              meaning:
                                type: string
                              reversed:
                                type: boolean
                    # NUMBER
                    number:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                      # PROPERTYSPEC
                      additionalProperties:
                        type: object
                        properties:
                          # ADDRESS
                          address:
                            type: object
                            x-kubernetes-preserve-unknown-fields: true
                            properties:
                              system:
                                type: string
                              instance:
                                type: string
            # STATUS
            status:
              type: object
              properties:
                # LASTUPDATED
                lastUpdated:
                    type: string
                    format: date-time

  scope: Namespaced
  names:
    plural: devices
    singular: device
    kind: Device
    shortNames:
      - dev
      - devs
